#!/usr/bin/env python3
"""coverage_map.py — cross-map corpus endpoints to mcecli code usage.

Reads the two inventories (re-generates them), greps mcecli source + endpoint
notes for each path prefix, and emits docs/dev/endpoint-inventory.md skeleton
with status column pre-filled:
  cmd      = curated mcecli command hits this path
  notes    = documented in endpoint-notes.md (verified/unverified)
  -        = no mcecli code reference (passthrough via `mcecli rest` still possible)
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CORPUS = Path.home() / "Documents/git-clones/sf-docs-scrap"
REF = CORPUS / "markdown/docs/marketing/marketing-cloud/references"
HEAD = re.compile(r"^#\s+(GET|POST|PUT|PATCH|DELETE)\s+(\S+)\s*$", re.M)

# curated mcecli commands → endpoint prefixes they own
CURATED = [
    ("de list/get", "data/v1/customObjects"),
    ("de rows/dump", "data/v1/customobjectdata"),
    ("de add", "data/v1/async/dataextensions"),
    ("asset", "asset/v1/content/assets"),
    ("query", "automation/v1/queries"),
    ("auto", "automation/v1/automations"),
    ("md", "interaction/v1/interactions"),
    ("rest (md/eventDefinitions)", "interaction/v1/eventDefinitions"),
    ("rest (schema)", "contacts/v1/schema"),
    ("api (discovery)", "v1/rest"),
]

def grep(pattern: str) -> bool:
    r = subprocess.run(
        ["grep", "-rl", "-i", pattern,
         "internal/", "docs/dev/endpoint-notes.md"],
        cwd=ROOT, capture_output=True, text=True)
    return r.returncode == 0 and bool(r.stdout.strip())

def main() -> None:
    out = ["# Endpoint inventory — corpus vs mcecli (generated)\n",
           "Generated by docs/dev/tools/coverage_map.py; annotations manual.",
           "Status: cmd = curated+tested · notes = documented · gap = not in mcecli\n"]
    total = covered = 0
    for sect_dir in sorted(REF.iterdir()):
        if not sect_dir.is_dir():
            continue
        rows = []
        for f in sorted(sect_dir.glob("*.md")):
            text = f.read_text(encoding="utf-8", errors="replace")
            m = HEAD.search(text)
            if not m:
                continue
            total += 1
            method, path = m.group(1), m.group(2)
            prefix = "/".join(path.split("/")[:3]).split("?")[0]
            hit_cmd = next((c for c, p in CURATED if prefix.startswith(p) or p in path), None)
            in_notes = grep(path.split("?")[0].replace("{", "").split("/")[0:3][-1]) if False else None
            # simpler: grep the literal first three path segments
            segs = "/".join(path.split("?")[0].split("/")[:3])
            hit_notes = grep(segs)
            if hit_cmd:
                status = f"cmd: {hit_cmd}"
                covered += 1
            elif hit_notes:
                status = "notes only"
                covered += 1
            else:
                status = "gap"
            rows.append((method, path, f.stem, status))
        if not rows:
            continue
        out.append(f"\n## {sect_dir.name}")
        out.append("| method | endpoint | doc | mcecli |")
        out.append("|---|---|---|---|")
        for method, path, stem, status in rows:
            out.append(f"| {method} | `{path}` | {stem} | {status} |")
    out.insert(4, f"Covered (cmd or notes): {covered}/{total}")
    (ROOT / "docs/dev/endpoint-inventory.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"written: docs/dev/endpoint-inventory.md — covered {covered}/{total}")

if __name__ == "__main__":
    main()
